### ISSUE TITLE
Server Connection Details are not saved

### ISSUE THREAD

**Issue by gowthamraj07** [biarms/pgadmin4#13]
I am using the following code in docker-compose (along with other images) to start pgAdmin in RPi 4. I noticed after every restart, the server connection details are not listed. Am I missing any configuration?

I tried using the volume like `/home/pi/pgAdmin:/pgadmin`. Still the same issue.

```
version: '3.3'

services:
    pgadmin:
        image: biarms/pgadmin4
        container_name: pgadmin
        privileged: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_CONFIG_SERVER_MODE=True
        ports:
            - "8050:5050"
 ```
